### ISSUE TITLE
Base vanishes when changing integrity with a Scanner Room connected.

### ISSUE THREAD

**Issue by MineKillerK** [SubnauticaNitrox/Nitrox#1823]
### Version

Latest commit of master branch (https://github.com/SubnauticaNitrox/Nitrox/commit/09a0a8309b418c66b75c51c00b47bd13fb2832a8)

### Bug

Half of the base (or even the entire base in some cases) including things such as moonpools completely vanish and very weird things occur. Trying to (de)construct anything afterwards results in it either getting stuck at 0%/100% or just no option to deconstruct. I can even fall out of the base. I've tried to fix it but couldn't find a way.

### Expected

If the base integrity is below 0 then I expect the base to get flooded. Otherwise nothing should happen and the base shouldn't vanish.

### Steps to reproduce

Some of these steps may not be 100% required or may be incorrect.
1. Build a Multipurpose Room.
2. Add something to the base that increases the integrity (e.g reinforcements).
3. Build a Scanner Room so that it connects to the base.
4. Remove the item you added in step 2 so that the integrity changes.  

### Other details

Restarting both the server and client does not fix the issue. I had to restore an older version of the `BaseData.json` file in order to fix the issue. Thankfully storage data is stored in a separate file so I didn't lose any items. 

Server logs didn't include any errors or warnings, however looking closely in the `player.log` file I found the following:
```
System.ArgumentException: Unable to locate recently built map room with Base(Clone) (Base)
  at NitroxClient.GameLogic.Bases.Spawning.BasePiece.MapRoomSpawnProcessor.FindUntaggedMapRoomFunctionality (Base latestBase) [0x00063] in <79a0f0042add47be8edc0866e96f6e39>:0 
  at NitroxClient.GameLogic.Bases.Spawning.BasePiece.MapRoomSpawnProcessor.SpawnPostProcess (Base latestBase, Int3 latestCell, UnityEngine.GameObject finishedPiece) [0x00007] in <79a0f0042add47be8edc0866e96f6e39>:0 
  at NitroxClient.GameLogic.Bases.Spawning.BasePiece.BasePieceSpawnProcessor.RunSpawnProcessor (TechType techType, Base latestBase, Int3 latestCell, UnityEngine.GameObject finishedPiece) [0x00024] in <79a0f0042add47be8edc0866e96f6e39>:0 
  at NitroxClient.GameLogic.Bases.Spawning.BasePiece.BasePieceSpawnProcessor.ReRunSpawnProcessor (UnityEngine.GameObject finishedPiece, NitroxModel.DataStructures.NitroxId nitroxId) [0x0000f] in <79a0f0042add47be8edc0866e96f6e39>:0 
  at NitroxClient.GameLogic.Bases.GeometryRespawnManager.UpdateBasePieceIdIfPossible (UnityEngine.GameObject gameObject, NitroxClient.GameLogic.Bases.GeometryRespawnManager+ObjectKey key) [0x00040] in <79a0f0042add47be8edc0866e96f6e39>:0 
  at NitroxClient.GameLogic.Bases.GeometryRespawnManager.BaseObjectRespawned (UnityEngine.GameObject gameObject) [0x00007] in <79a0f0042add47be8edc0866e96f6e39>:0 
  at NitroxPatcher.Patches.Dynamic.Base_SpawnPiece_Patch.Postfix (Base __instance, UnityEngine.Transform __result) [0x0001f] in <62b3fc1165c24ba79747d7f8a12da537>:0 
  at (wrapper dynamic-method) Base.DMD<Base::SpawnPiece>(Base,Base/Piece,Int3,UnityEngine.Quaternion,System.Nullable`1<Base/Direction>)
  at Base.BuildMapRoomGeometry (Int3 cell, System.Int32 index, Base+CellType cellType) [0x0004a] in <b20a3a5ada624fe2a1501d935cca65f7>:0 
  at Base.BuildGeometryForCell (Int3 cell) [0x0007f] in <b20a3a5ada624fe2a1501d935cca65f7>:0 
  at Base.BuildGeometry () [0x00019] in <b20a3a5ada624fe2a1501d935cca65f7>:0 
  at Base.RebuildGeometry () [0x00088] in <b20a3a5ada624fe2a1501d935cca65f7>:0 
  at (wrapper dynamic-method) Base.DMD<Base::CopyFrom>(Base,Base,Int3/Bounds,Int3)
  at (wrapper dynamic-method) BaseGhost.DMD<BaseGhost::Finish>(BaseGhost)
  at (wrapper dynamic-method) ConstructableBase.DMD<ConstructableBase::SetState>(ConstructableBase,bool,bool)
  at (wrapper dynamic-method) Constructable.DMD<Constructable::Construct>(Constructable)
  at ConstructableBase.Construct () [0x0001f] in <b20a3a5ada624fe2a1501d935cca65f7>:0 
  at BuilderTool.Construct (Constructable c, System.Boolean state) [0x0005d] in <b20a3a5ada624fe2a1501d935cca65f7>:0 
  at (wrapper dynamic-method) BuilderTool.DMD<BuilderTool::HandleInput>(BuilderTool)
  at BuilderTool.OnLeftHandHeld () [0x00000] in <b20a3a5ada624fe2a1501d935cca65f7>:0 
  at GUIHand.OnUpdate () [0x002e6] in <b20a3a5ada624fe2a1501d935cca65f7>:0 
  at ManagedUpdate.Execute (ManagedUpdate+Queue queue) [0x00027] in <b20a3a5ada624fe2a1501d935cca65f7>:0 
```

## Screenshots
![Screenshot_20220617_184922](https://user-images.githubusercontent.com/77889699/174333363-e7a31e56-1d51-4b4c-bfd5-89179fcaeab5.png)
![Screenshot_20220617_184931](https://user-images.githubusercontent.com/77889699/174333378-300d76df-34fd-4bb7-aade-292053a3fee9.png)
![Screenshot_20220617_184939](https://user-images.githubusercontent.com/77889699/174333402-499fa4c2-fff4-4a31-95b6-c65302a30428.png)
![Screenshot_20220617_184947](https://user-images.githubusercontent.com/77889699/174333410-03adacff-17c6-411a-9dc1-bf297f71266e.png)
![Screenshot_20220617_184957](https://user-images.githubusercontent.com/77889699/174333425-31ba35fb-93b1-4251-a5fe-e7606ff26440.png)

**Comment by tornac1234** [comment]
This is a known issue and will be fixed with #1819

**Comment by Crapy** [comment]
> This is a known issue and will be fixed with #1819

Tested it, still an issue. When creating a scanner room the rest of the players will suddenly walk inside the water (with fall damage and everything), fish and fragments disappear, this continues until the scanner room is removed

**Comment by tornac1234** [comment]
> > This is a known issue and will be fixed with #1819
> 
> Tested it, still an issue. When creating a scanner room the rest of the players (Not the creator) will suddenly walk inside the water (with fall damage and everything), fish and fragments disappear, this continues until the scanner room is removed

I re-tested it myself and it works. Are you sure you tested my branch and not the current master ? because this PR is still not merged

**Comment by Crapy** [comment]
> > > This is a known issue and will be fixed with #1819
> > 
> > 
> > Tested it, still an issue. When creating a scanner room the rest of the players (Not the creator) will suddenly walk inside the water (with fall damage and everything), fish and fragments disappear, this continues until the scanner room is removed
> 
> I re-tested it myself and it works. Are you sure you tested my branch and not the current master ? because this PR is still not merged

Have you tested it with other people? You can see my fork where I merged this PR and tested it

**Comment by tornac1234** [comment]
Yes I tested with 2 local players and nothing went wrong. I looked at your fork and it looks a bit messy because you took stuff from different PRs, which you shouldn't because it quickly becomes highly experimental. Maybe you could just use the `gh pr checkout 1819` command to only test this PR ?

**Comment by Crapy** [comment]
> Yes I tested with 2 local players and nothing went wrong. I looked at your fork and it looks a bit messy because you took stuff from different PRs, which you shouldn't because it quickly becomes highly experimental. Maybe you could just use the `gh pr checkout 1819` command to only test this PR ?

I will, however I only merged your sync-ping-signals and this when I tested, the rest were added afterwards, do you see any reason both of these PRs would collide? Have you tested it with both of them?

**Comment by tornac1234** [comment]
I'm pretty sure they have nothing in common but we still can't be sure that the branch you made up from different stuff will work as intended

**Comment by Crapy** [comment]
> I'm pretty sure they have nothing in common but we still can't be sure that the branch you made up from different stuff will work as intended

You are right, I'll do a checkout specifically for this. Thank you for your work.
