### ISSUE TITLE
[current master] base pieces are not deconstructable

### ISSUE THREAD

**Issue by Her0brineCreeper** [SubnauticaNitrox/Nitrox#951]
While testing the current version of the Nitrox mod compiled from master, we noticed that deconstructed base pieces respawned after rejoining, so I started trying to fix this issue.
The first thing I did was adding some code to BaseManager.cs in order to make deconstruction work on the server side (I just copied the code from "DeconstructionBegin" to "BasePieceConstructionAmountChanged"), because the "DeconstructionBegin" packet isn't send by the client (yet?). After this deconstruction of lonely base pieces worked fine, but the ones in bases were sill not deconstructable. After more testing and searching I found the exact cause of this issue:
Whenever a base piece is finished constructing, the other ones in its base will also be "reconstructed" and get a new id. This leads to two problems:
- The ids of the old pieces change so when they get deconstructed, the id sent to the server to deconstruct isn't the same one the server has assigned to this piece.
- The gameObjects come in in a random? order, so that the latest one to which the id of the ghost is assigned, isn't the right one most of the time.

I found this out by writing the ids and the type of base piece to the log.
Here is an example log output where I added a L pice to an existing base:
```
[00:14:56 Client INFO]: Constructed 9272f502-3d4e-4728-9dd1-b1aa0e59bf70; /BaseCorridorL(Clone)/BaseGhost/BaseCell(Clone)/BaseCorridorLShape(Clone)
[00:14:56 Client INFO]: Constructed e1a8433b-d576-4ff5-9c4b-7ccff07fe193; /BaseCorridorL(Clone)/BaseGhost/BaseCell(Clone)/BaseCorridorLShape(Clone)
[00:14:56 Client INFO]: Constructed 2fd5f653-e801-4507-a7b9-33a8ea545082; /BaseCorridorL(Clone)/BaseGhost/BaseCell(Clone)/BaseCorridorLShape(Clone)
[00:14:59 Client INFO]: Constructed e006aa91-1653-460c-b653-7f6ec6ea27f3; /BaseCorridorL(Clone)/BaseGhost/BaseCell(Clone)/BaseCorridorLShape(Clone)
[00:15:00 Client INFO]: Constructed 341360fe-baa5-45f7-a9f7-82f0c4516e5d; /BaseCorridorL(Clone)/BaseGhost/BaseCell(Clone)/BaseCorridorLShape(Clone)
[00:15:00 Client INFO]: Constructed d391cfe6-7d07-4311-a3b2-cf4a135dbf4b; /Landscape/Global Root/Base(Clone)/BaseCell(Clone)/BaseCorridorLShape(Clone)
[00:15:00 Client INFO]: Constructed 336a04b0-01bd-44b6-859a-a56d73bd5e87; /Landscape/Global Root/Base(Clone)/BaseCell(Clone)/BaseCorridorTShape(Clone)
[00:15:00 Client INFO]: Constructed 27ab8e1a-e354-4a4a-8858-2936108f4e16; /Landscape/Global Root/Base(Clone)/BaseCell(Clone)/BaseCorridorLShape(Clone)
[00:15:00 Client INFO]: Constructed 53a54d37-e3f3-4e4e-b06e-65076b4a673d; /Landscape/Global Root/Base(Clone)/BaseCell(Clone)/BaseCorridorTShape(Clone)
[00:15:00 Client INFO]: Constructed 7317b01c-4acc-42f0-ad14-2b795a8a0636; /Landscape/Global Root/Base(Clone)/BaseCell(Clone)/BaseCorridorXShape(Clone)
[00:15:00 Client DEBUG]: ghost id: 4b9502c9-c85d-49f1-9f3b-699b09547127
[00:15:00 Client DEBUG]: finishedPiece id: 7317b01c-4acc-42f0-ad14-2b795a8a0636; /Landscape/Global Root/Base(Clone)/BaseCell(Clone)/BaseCorridorXShape(Clone)
```
At this point I gave up on trying to fix this bug, because I couldn't do anything against the game doing this and I couldn't find a way to code a workaround for this behavior. It could be possible by filtering the newly created basePieces somehow, changing the ids of the old ones that were already completed to the ones they should have and giving the one piece that is left after this the id of the ghost. Since I don't have enough time and especially not enough knowledge about C# programming I decided to just tell you about this issue and hope you can fix it soon.
Thank you for making multiplayer possible for this awesome game and keeping up the work on the project.

**Comment by Sunrunner37** [comment]
Hello, thanks for the very detail report.  Were you able to identify the code path that was triggering a reconstruction of children?

**Comment by Sunrunner37** [comment]
I think we attempted to solve this once before by copying over the ids when the base geometry changes:

https://github.com/SubnauticaNitrox/Nitrox/blob/master/NitroxPatcher/Patches/Dynamic/Base_SpawnPiece_Patch.cs

https://github.com/SubnauticaNitrox/Nitrox/blob/master/NitroxPatcher/Patches/Dynamic/Base_ClearGeometry_Patch.cs

However, these patches are likely not working as intended.

**Comment by Sunrunner37** [comment]
So I pushed a fix for two bugs: 

1) We were not sending the DeconstructionBegin event
2) We were referencing the UniqueIdentifier instead of NitroxId when trying to copy over the ids to the refreshed base pieces.  

See commit: https://github.com/SubnauticaNitrox/Nitrox/commit/adab632fe5ffd24b3b55831315d6dee354cc10d2

**Comment by Her0brineCreeper** [comment]
Thank you very much for the quick answer and the fix for the two bugs. I will test later if everything works fine now.

**Comment by Sunrunner37** [comment]
A few updates on this.  Unfortunately, there is much, much more going on under the hood that is causing base problems. 

Previously we were relying on BaseDeconstructable instantiation to get a reference to the newest base piece before sending it to other clients.  However, geometry rebuilding causes this to be triggered for all base pieces so the reference is normally incorrect.  One potential solution was to find the new piece in base geometry rebuilding (one we haven't seen before) however, this logic is triggered for all component pieces as well (such as a cap for a connector) and there is no good way to identify which pieces we are interested in.  I ended up recording the cell that the ghost was placed in using BaseGhost.Place - if a cell does not exist than we know this is the first base piece and can simply record the piece.

Additionally, we were not sending deconstruction packets correctly because they were being sent from the BaseDeconstructable deconstructor.  As we know, this is also triggered each time a base piece rebuilds geometry.  I put it in a more appropriate place which is Constructable.SetState() and added a check for a change from true to false.

Lastly, in the deconstruction begin patch, we needed to correctly differentiate between furniture and base pieces - the latter has DeconstructableBase and the former Constructable.  

You can find these changes in: https://github.com/SubnauticaNitrox/Nitrox/commit/6393f335b798e151968e6aad228fef16996eca4d

These seem to make base building more reliable.  However, there are still a few kinks to work out in regards to rotational metadata, deconstructing the last base piece, and some of the special base pieces.

**Comment by Her0brineCreeper** [comment]
After testing your new changes a little bit I found out that the deconstruction of small bases works fine now. But when building bigger bases and trying to deconstruct them afterwards, some pieces still don't have the right ID and don't get deconstructed on the server because of this. The strangest thing about this is that some of the pieces get the ID of another piece of that base, so if I deconstruct an I piece for example, the server receives the ID to deconstruct some random X piece from that base. I didn't have time to track down the cause of this problem yet but my best guess is that it has something to do with the SpawnPiece method accessing the "NitroxIdByObjectKey" Dictionary at the same time the ClearGeometry is writing to it, because all the code that should update the IDs of the base pieces looks fine.
If you know how to fix this problem but don't have time to do it yourself, please tell me what the cause is, because I could do it then. Otherwise I'll try to fix it later this day on my own. (It's currently morning in Germany where I live)

**Comment by Her0brineCreeper** [comment]
Since you committed more changes related to the deconstructing now, I'll test them this afternoon and tell you how good it works now.

**Comment by Her0brineCreeper** [comment]
I just tested your latest commits and construction and deconstruction of base pieces works good enough to be usable in normal playing now. 
There are still two little bugs I noticed, but they can simply be fixed by reconnecting and trying again, which for sure isn't a permanent solution, but good enough to make the base building usable:
- Sometimes the construction of base pieces doesn't complete on the server so after reconnecting they are just ghosts again and need to be completed again. I think this happens because the client still sends the wrong IDs rarely, but it could also have some other reason.
- A few base pieces still don't get deconstructed on the server which I think is also caused by the client having a wrong ID assigned to that piece.

Thank you very much for helping me with this issue and working on a fix for it instantaneously. Now me and my friend can continue testing this mod, trying to complete the game and finish our base.

**Comment by Sunrunner37** [comment]
Thank you for testing the latest change - it is very helpful to have someone who is technical help out in the testing process.  

I found a major issue when constructing base pieces that have faces (hatches, windows, etc).  Since we look up the most recent base piece by cell, we were resolving the first piece that built in that cell.  Building faces would result in us overriding the id on a previous piece causing very weird problems for the base.  

The fix for this issue was to scan the cell for the latest piece.  The criteria for scanning is anything that is deconstructable by the player (i.e. BaseDeconstructable) and missing a NitroxEntity. After this fix, hatches are properly buildable and deconstructable without issue.   See the latest changes here: https://github.com/SubnauticaNitrox/Nitrox/commit/016ddf413916e9d169c150ac484c63f15fdd2834

**Comment by Her0brineCreeper** [comment]
While playing together with my friend yesterday (on c0d478d6796778ea3ac0431885bc9db81b1ffb43 because the three new commits weren't there yet), I noticed another issue with the base building. Like I wrote before, some pieces still don't complete construction properly. After rejoining they are ghosts again. But the strangest thing was that it was not possible to finish constructing them after this no matter how often I tried it. The only possibility was to deconstruct those pieces and completely rebuild them which worked fine. I couldn't figure out what caused this issue, but it has to have something to do with wrong Ids being sent again.

**Comment by 8BallBomBom** [comment]
Experienced the same issue testing some days ago, also had it where a bio reactor ghost spawned floating outside the habitat, couldn't deconstruct or interact with it.
Ended up starting fresh.

**Comment by Her0brineCreeper** [comment]
We just noticed that it is also impossible to construct the moonpool, because you can never finish constructing it. Whenever you reconnect it returns to its ghost state. Neither trying again after reconnecting nor deconstructing and placing it again fixes this problem. This may also apply to the other bigger base rooms like the Multipurpose Room or the Observatory Room but I didn't test this.

**Comment by Sunrunner37** [comment]
@Her0brineCreeper Can you try with the current version of master?  I've pushed several different fixes today that should make base building more stable.

**Comment by JustinHoeky** [comment]
@Sunrunner37 could you point me in a direction to build the latest master version? 
I'm willing to test it out if needed like @Her0brineCreeper is doing.

That being said, what would you like us to test? Will try to report back as detailed as possible

**Comment by Her0brineCreeper** [comment]
@Sunrunner37 
I just tested your latest changes and I have bad news: Sometimes just adding a second base piece to a base causes the client to somehow lose the right id for this one. It sends the "AddBasePiece" packet to the server correctly, but the "BasePieceConstructionComleted" packet contains the wrong id, so the server is unable to finish construction of that piece. Even reconnecting multiple times doesn't get the client to send the right id when construction is completed, so it always resets to its ghost state. This seems to happen more often than before your latest changes. I didn't do any more testing yet because this is a major issue, which makes deeper testing difficult.

**Comment by Sunrunner37** [comment]
@Her0brineCreeper Thanks for the reply.  Can you tell me the exact pieces you are using for your testing?

**Comment by Her0brineCreeper** [comment]
Most of the time I am testing using the simple tube-like pieces and in creative mode (if this matters).
I've just done some more testing and I found a really strange behavior: I could never get the second base pieces to build properly except when I added the second base piece to the side which was in front of me while building the first one. This way I was even able to build a long tunnel of I-Pieces without problems. For pieces with more than two connections, the one you are looking at while placing the ghost piece and the one pointing to left work, the other ones don't. Based on this findings I think this issue has something to do with the rotation of the pieces. I hope this information is helpful for you.

**Comment by Sunrunner37** [comment]
Ahh I see... the current implementation has some edge cases that do not work in creative mode.  I usually test with 'nocost' instead.  Fast building (creative/bobthebuilder) seem to omit packets.

**Comment by JustinHoeky** [comment]
@Sunrunner37 I see your latest commit about the TargetBaseOffset is what @Her0brineCreeper is talking about. I will try to build a new master and test it and see if i can be of any use.

**Comment by Her0brineCreeper** [comment]
I just did some testing again because I wanted to try out building in survival mode. I used your latest commit for this and everything worked almost flawless. The construction AND deconstruction of all the normal base pieces (tubes & rooms) worked without any problems. Even all the indoor and outdoor parts (solar panels, reactors, lockers) were usable without any problems. And the strangest part of this is, that it all also worked fine in creative, which seems to be related to your latest commit. Now there were only two problems left I noticed while testing:
- One can only add around 2 or 3 base windows and reinforcements to a multipurpose room, adding more causes them to become stucked ghosts which you are neither able to complete nor deconstruct and which spawn not attached to the room after reconnecting.
- After rejoining while standing inside of a base, you are swimming and lose oxygen. When using the hatch then, the animation of entering a base plays and everything works fine again.

**Comment by dikho11** [comment]
hello, may i ask if this version of nitrox is the best?
 https://nitrox.rux.gg/

**Comment by Her0brineCreeper** [comment]
For general use the version from the website you sent is recommended. For testing and fixing of bugs we are using the current master. It contains the latest features and bugfixes but isn't as easy to use and receives updates almoat daily. Like I said before on the current master the building issues are mostly fixed now. If you want to try it out, you can follow this guide to set up a development environment for Nitrox and compile the latest master yourself.
https://github.com/SubnauticaNitrox/Nitrox/wiki/Setting-up-a-development-environment-for-Nitrox

**Comment by dikho11** [comment]
tbh I have no idea about code so prob just stick to my normal version, but thanks for all your help guys  
its a really nice and helpful community you have built over the years

**Comment by acidscorch** [comment]
@Her0brineCreeper @Sunrunner37 
All the things you mentioned are correct. Transferring Ids is currently broken. As Sunrunner already implemented partly fixes, this theme is very complex, because of adding or removing objects to a Base can change other objects and/or the complete Layout of the Base. I'm currently working on the fix for all Base related stuff and need someone who could Test and Verify the changes. @Her0brineCreeper 
 Please give a reply if you would be interested in testing upcoming pull-request.

Best Regards

**Comment by dartasen** [comment]
Would need more recent testing
